language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

script:
  # Run tests
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release